project_id = "yofhrfahhzsxbtuhuwqf"

[functions.generate-prediction]
verify_jwt = false

[functions.fetch-live-matches]
verify_jwt = false

[functions.fetch-upcoming-matches]
verify_jwt = false

[functions.generate-daily-predictions]
verify_jwt = false

[functions.fetch-user-performance]
verify_jwt = false

[functions.mpesa-stk-push]
verify_jwt = false

[functions.mpesa-webhook]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false

[functions.fetch-api-football]
verify_jwt = false

[functions.cron-hourly-fixtures]
verify_jwt = false

[functions.cron-daily-predictions]
verify_jwt = false

[functions.daily-predictions-automation]
verify_jwt = false

[functions.update-prediction-results]
verify_jwt = false

[functions.cron-subscription-reminders]
verify_jwt = false

[functions.apply-referral-on-signup]
verify_jwt = false

[functions.spin-wheel]
verify_jwt = false

[functions.activate-subscription]
verify_jwt = false

[functions.fetch-match-context]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
