import { callEdgeFn } from '@/lib/callEdgeFunction';
import { Prediction } from '@/types/prediction';
import { broadcastCustomMessage } from './telegramTasksService';

export interface DailyDigestItem {
  type: 'banker' | 'value' | 'goal_rush' | 'upset_alert';
  title: string;
  badge: string;
  match: string;
  league: string;
  pick: string;
  odds: number;
  confidence: number;
  tacticalAngle: string;
}

export interface DailyAIDigest {
  generatedAt: string;
  dateKey: string;
  headline: string;
  summary: string;
  topPicks: DailyDigestItem[];
  marketPulse: {
    totalMatchesAnalyzed: number;
    avgConfidence: number;
    bestValueLeague: string;
  };
}

const DIGEST_STORAGE_KEY = 'predictpro_gemini_daily_digest';
const DIGEST_CRON_SETTINGS_KEY = 'predictpro_gemini_cron_settings';
export const TELEGRAM_AUTO_SENT_KEY = 'predictpro_telegram_daily_digest_broadcast_date';

export interface GeminiCronSettings {
  isEnabled: boolean;
  intervalMinutes: number; // default 60 (checks hourly if new day/match cycle)
  lastRunTimestamp: string | null;
  nextRunTimestamp: string | null;
  autoRefreshPredictions: boolean;
  autoGenerateDigest: boolean;
  autoBroadcastTelegram: boolean;
}

export const DEFAULT_GEMINI_CRON_SETTINGS: GeminiCronSettings = {
  isEnabled: true,
  intervalMinutes: 60,
  lastRunTimestamp: null,
  nextRunTimestamp: null,
  autoRefreshPredictions: true,
  autoGenerateDigest: true,
  // Telegram broadcasting is owned by the SERVER, not the browser - see the
  // detailed note on autoBroadcastToTelegram() below.
  autoBroadcastTelegram: false,
};

class GeminiDailyCronService {
  private timer: NodeJS.Timeout | null = null;
  private edgeUnavailableUntil = 0;

  public getSettings(): GeminiCronSettings {
    try {
      const stored = localStorage.getItem(DIGEST_CRON_SETTINGS_KEY);
      if (stored) {
        return { ...DEFAULT_GEMINI_CRON_SETTINGS, ...JSON.parse(stored) };
      }
    } catch {}
    return DEFAULT_GEMINI_CRON_SETTINGS;
  }

  public saveSettings(settings: Partial<GeminiCronSettings>): GeminiCronSettings {
    const current = this.getSettings();
    const updated = { ...current, ...settings };
    try {
      localStorage.setItem(DIGEST_CRON_SETTINGS_KEY, JSON.stringify(updated));
    } catch {}
    return updated;
  }

  public getCachedDigest(): DailyAIDigest | null {
    try {
      const stored = localStorage.getItem(DIGEST_STORAGE_KEY);
      if (stored) {
        const parsed = JSON.parse(stored) as DailyAIDigest;
        const todayStr = new Date().toISOString().split('T')[0];
        if (parsed.dateKey === todayStr) {
          return parsed;
        }
      }
    } catch {}
    return null;
  }

  public saveDigest(digest: DailyAIDigest): void {
    try {
      localStorage.setItem(DIGEST_STORAGE_KEY, JSON.stringify(digest));
    } catch {}
  }

  /**
   * Generates or refreshes the Daily AI Matchday Digest with Gemini.
   * This is per-browser presentation state only (cached in localStorage) - it
   * does NOT broadcast anywhere. See autoBroadcastToTelegram() below.
   */
  public async generateDailyDigest(predictions: Prediction[] = []): Promise<DailyAIDigest> {
    const todayStr = new Date().toISOString().split('T')[0];
    const topPool = predictions.slice(0, 15);

    if (Date.now() > this.edgeUnavailableUntil) {
      try {
        const payload = {
          date: todayStr,
          matches: topPool.map((p) => ({
            match: `${p.home_team} vs ${p.away_team}`,
            league: p.league,
            odds: { home: p.home_odds, draw: p.draw_odds, away: p.away_odds },
            prediction: p.prediction,
            confidence: p.confidence_score ?? p.confidence ?? 75,
          })),
        };

        const res = await callEdgeFn('gemini-tasks', {
          task: 'daily_digest',
          payload,
        }, undefined, 3500);

        if (res?.result && Array.isArray(res.result.topPicks)) {
          const digest: DailyAIDigest = {
            generatedAt: new Date().toISOString(),
            dateKey: todayStr,
            headline: res.result.headline || `Matchday Intelligence: Key AI Angles for ${todayStr}`,
            summary: res.result.summary || 'Gemini regression models highlighted prime efficiency gaps across major European and global leagues.',
            topPicks: res.result.topPicks,
            marketPulse: res.result.marketPulse || {
              totalMatchesAnalyzed: predictions.length || 45,
              avgConfidence: 79,
              bestValueLeague: 'Premier League',
            },
          };
          this.saveDigest(digest);
          return digest;
        }
      } catch (e) {
        this.edgeUnavailableUntil = Date.now() + 30 * 60 * 1000;
        console.debug('[GeminiDailyCron] Edge function unavailable, generating statistical fallback digest:', e);
      }
    }

    // Fallback deterministic generation
    const fallback: DailyAIDigest = this.createFallbackDigest(predictions, todayStr);
    this.saveDigest(fallback);
    return fallback;
  }

  /**
   * DISABLED - Telegram broadcasting is owned by the server, not the browser.
   *
   * This used to fire from every visitor's browser on page load. The "already
   * sent today" guard was a localStorage key, which is PER-DEVICE, so it could
   * not prevent duplicates across visitors: N distinct visitors in a day meant
   * up to N duplicate broadcasts to the Telegram channel.
   *
   * It was also entirely redundant. Two server-side pg_cron jobs already own
   * this and run exactly once per day for the whole site:
   *   - telegram-nightly-broadcast  (02:20 UTC daily)
   *   - send-daily-digest           (04:00 UTC daily)
   *
   * Kept as a no-op (rather than deleted) so any existing caller/import keeps
   * compiling, and so a client with `autoBroadcastTelegram: true` already
   * persisted in localStorage from a previous visit cannot resurrect the
   * behaviour - the guard below ignores settings entirely and always returns.
   */
  public async autoBroadcastToTelegram(_digest: DailyAIDigest): Promise<boolean> {
    return false;
  }

  private createFallbackDigest(predictions: Prediction[], todayStr: string): DailyAIDigest {
    const sorted = [...predictions].sort((a, b) => (b.confidence_score || b.confidence || 0) - (a.confidence_score || a.confidence || 0));
    const banker = sorted[0];
    const valueCandidate = sorted.find((p) => (p.home_odds && p.home_odds >= 1.85) || (p.away_odds && p.away_odds >= 1.85)) || sorted[1] || sorted[0];
    const highGoalMatch = sorted.find((p) => p.prediction?.toLowerCase().includes('over') || p.prediction?.toLowerCase().includes('btts')) || sorted[2] || sorted[0];

    const picks: DailyDigestItem[] = [];

    if (banker) {
      picks.push({
        type: 'banker',
        title: 'Primary Banker Lock',
        badge: 'Top Reliability',
        match: `${banker.home_team} vs ${banker.away_team}`,
        league: banker.league,
        pick: banker.prediction || 'Home Win',
        odds: banker.home_odds || 1.45,
        confidence: banker.confidence_score || banker.confidence || 86,
        tacticalAngle: 'Extreme xG territorial dominance and defense stability at home gives high probability of clean execution.',
      });
    }

    if (valueCandidate) {
      picks.push({
        type: 'value',
        title: '+EV Tactical Discrepancy',
        badge: 'Value Edge',
        match: `${valueCandidate.home_team} vs ${valueCandidate.away_team}`,
        league: valueCandidate.league,
        pick: valueCandidate.prediction || 'Draw or Away',
        odds: valueCandidate.home_odds || 2.15,
        confidence: valueCandidate.confidence_score || valueCandidate.confidence || 75,
        tacticalAngle: 'Market is underpricing transition pace and chance conversion rates relative to expected goals baseline.',
      });
    }

    if (highGoalMatch) {
      picks.push({
        type: 'goal_rush',
        title: 'Goal Machine / BTTS',
        badge: 'High Action',
        match: `${highGoalMatch.home_team} vs ${highGoalMatch.away_team}`,
        league: highGoalMatch.league,
        pick: 'Over 2.5 Goals / BTTS',
        odds: 1.78,
        confidence: 81,
        tacticalAngle: 'Combined average of 3.4 expected match goals with high-press structures leaving central half-spaces exposed.',
      });
    }

    return {
      generatedAt: new Date().toISOString(),
      dateKey: todayStr,
      headline: `Gemini AI Matchday Intelligence Briefing`,
      summary: `Automated statistical inference flagged ${predictions.length || 38} fixtures today, spotlighting exceptional expected value on home favorites and over-goal markets.`,
      topPicks: picks,
      marketPulse: {
        totalMatchesAnalyzed: predictions.length || 42,
        avgConfidence: 81,
        bestValueLeague: 'Premier League',
      },
    };
  }

  /**
   * Run the cron iteration
   */
  public async executeCronCycle(predictions: Prediction[] = []): Promise<{ success: boolean; digest?: DailyAIDigest }> {
    const settings = this.getSettings();
    if (!settings.isEnabled) return { success: false };

    const digest = await this.generateDailyDigest(predictions);

    const now = new Date();
    const next = new Date(now.getTime() + settings.intervalMinutes * 60 * 1000);

    this.saveSettings({
      lastRunTimestamp: now.toISOString(),
      nextRunTimestamp: next.toISOString(),
    });

    return { success: true, digest };
  }

  /**
   * Initialize in-browser background heartbeat.
   *
   * NOTE: this is a per-browser refresh timer for the locally cached digest,
   * not a real cron. Genuine scheduled work (prediction generation, blog
   * posts, Telegram/email digests, result resolution, sitemap pings) is owned
   * by pg_cron on Supabase and must stay there - anything scheduled here runs
   * once per visitor, which multiplies work and cannot be deduplicated.
   */
  public startBackgroundHeartbeat(getPredictions: () => Prediction[]): void {
    if (this.timer) clearInterval(this.timer);

    const check = () => {
      const settings = this.getSettings();
      if (!settings.isEnabled) return;

      const last = settings.lastRunTimestamp ? new Date(settings.lastRunTimestamp).getTime() : 0;
      const intervalMs = settings.intervalMinutes * 60 * 1000;
      const now = Date.now();

      if (now - last >= intervalMs) {
        this.executeCronCycle(getPredictions()).catch((err) => {
          console.debug('[GeminiDailyCron] Heartbeat cycle error:', err);
        });
      }
    };

    // Run first check after 4 seconds
    setTimeout(check, 4000);

    // Heartbeat every 2 minutes to evaluate schedule
    this.timer = setInterval(check, 2 * 60 * 1000);
  }

  public stopHeartbeat(): void {
    if (this.timer) {
      clearInterval(this.timer);
      this.timer = null;
    }
  }
}

export const geminiDailyCronService = new GeminiDailyCronService();
