import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response(null, { headers: corsHeaders });

  try {
    const body = await req.json();
    const {
      action = 'broadcast',
      message,
      parse_mode = 'HTML',
      channel,
      prediction,
      banker,
      acca,
      valueBet,
      liveInplay,
    } = body;

    const botToken = Deno.env.get('TELEGRAM_BOT_TOKEN');
    const defaultChatId = Deno.env.get('TELEGRAM_CHAT_ID') || '@predictproAi';
    const chatId = channel || defaultChatId;

    // Task 1: Check Bot & Channel Health
    if (action === 'check_bot') {
      if (!botToken) {
        return new Response(JSON.stringify({
          success: false,
          configured: false,
          message: 'TELEGRAM_BOT_TOKEN is not set in environment secrets.',
          defaultChatId,
        }), {
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        });
      }

      try {
        const meRes = await fetch(`https://api.telegram.org/bot${botToken}/getMe`);
        const meData = await meRes.json();

        let chatData: any = null;
        try {
          const chatRes = await fetch(`https://api.telegram.org/bot${botToken}/getChat?chat_id=${encodeURIComponent(chatId)}`);
          chatData = await chatRes.json();
        } catch {}

        return new Response(JSON.stringify({
          success: meRes.ok,
          configured: true,
          bot: meData?.result,
          channel: chatData?.result ?? { chat_id: chatId },
          chatId,
        }), {
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        });
      } catch (err: any) {
        return new Response(JSON.stringify({
          success: false,
          configured: true,
          error: err.message,
        }), {
          status: 500,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        });
      }
    }

    // Build message text based on action task
    let textToSend = message;

    // Task 2: Broadcast Banker Bet
    if (action === 'send_banker' && banker) {
      const home = banker.home_team || 'Home';
      const away = banker.away_team || 'Away';
      const league = banker.league || 'Top League';
      const outcome = banker.predicted_outcome || banker.prediction || 'Home Win';
      const odds = banker.odds || banker.home_odds || 1.85;
      const confidence = banker.confidence_score || banker.confidence || 82;
      const reasoning = banker.reasoning || banker.analysis || 'High-probability mathematical edge backed by recent form and tactical matchup.';

      textToSend = [
        `🎯 <b>PREDICTPRO AI — BANKER OF THE DAY</b> 🎯`,
        ``,
        `⚽ <b>${home} vs ${away}</b>`,
        `🏆 <i>${league}</i>`,
        `📊 <b>Pick:</b> ${outcome}`,
        `💰 <b>Odds:</b> ${Number(odds).toFixed(2)}`,
        `🔥 <b>AI Confidence:</b> ${confidence}%`,
        ``,
        `🧠 <b>AI Analysis:</b>`,
        `${reasoning}`,
        ``,
        `⚡ <i>Generated by PredictPro Gemini AI Engine</i>`,
        `🔗 Track live & see more picks: https://predictpro.guru`,
        `⚠️ <i>Gamble responsibly. 18+ only.</i>`,
      ].join('\n');
    }

    // Task 3: Broadcast Match Prediction
    if (action === 'send_prediction' && prediction) {
      const home = prediction.home_team || 'Home';
      const away = prediction.away_team || 'Away';
      const league = prediction.league || 'League';
      const outcome = prediction.predicted_outcome || prediction.prediction || 'Match Pick';
      const confidence = prediction.confidence_score || prediction.confidence || 75;
      const correctScore = prediction.correct_score || prediction.metadata?.correct_score || 'N/A';
      const homeOdds = prediction.home_odds ? Number(prediction.home_odds).toFixed(2) : '-';
      const drawOdds = prediction.draw_odds ? Number(prediction.draw_odds).toFixed(2) : '-';
      const awayOdds = prediction.away_odds ? Number(prediction.away_odds).toFixed(2) : '-';
      const analysis = prediction.analysis || prediction.reasoning || '';

      textToSend = [
        `🔮 <b>PREDICTPRO AI MATCH PREDICTION</b>`,
        ``,
        `⚔️ <b>${home} vs ${away}</b>`,
        `🏆 ${league}`,
        `🎯 <b>Prediction:</b> <u>${outcome}</u> (${confidence}% Confidence)`,
        `🔢 <b>Projected Score:</b> ${correctScore}`,
        `📈 <b>1X2 Odds:</b> 1: ${homeOdds} | X: ${drawOdds} | 2: ${awayOdds}`,
        analysis ? `\n💡 <b>Tactical Note:</b>\n${analysis}\n` : '',
        `👉 View full analytics: https://predictpro.guru`,
      ].filter(Boolean).join('\n');
    }

    // Task 4: Broadcast Accumulator Slip
    if (action === 'send_acca' && acca) {
      const title = acca.title || 'AI MULTI-MATCH ACCUMULATOR';
      const selections = acca.selections || [];
      const totalOdds = acca.totalOdds ? Number(acca.totalOdds).toFixed(2) : '3.50';
      const estReturn = acca.estimatedPayout ? Number(acca.estimatedPayout).toFixed(2) : null;

      const legsFormatted = selections.map((s: any, idx: number) => {
        return `${idx + 1}. <b>${s.homeTeam || s.match} vs ${s.awayTeam || ''}</b>\n   👉 <b>${s.market}</b> @ ${Number(s.odds).toFixed(2)} (${s.confidence || 70}% Conf)`;
      }).join('\n\n');

      textToSend = [
        `🚀 <b>PREDICTPRO ${title.toUpperCase()}</b> 🚀`,
        ``,
        legsFormatted,
        ``,
        `💎 <b>Total Combined Odds:</b> ${totalOdds}`,
        estReturn ? `💵 <b>Est. Return (1,000 KES Stake):</b> KES ${estReturn}` : '',
        ``,
        `⚡ <i>Curated with PredictPro Gemini AI Engine</i>`,
        `📲 Build your own custom slips: https://predictpro.guru/accumulator`,
      ].filter(Boolean).join('\n');
    }

    // Task 5: Broadcast Positive Expected Value (EV) Bet
    if (action === 'send_value_bet' && valueBet) {
      const home = valueBet.home_team || 'Home';
      const away = valueBet.away_team || 'Away';
      const league = valueBet.league || 'League';
      const market = valueBet.market || 'Value Pick';
      const odds = Number(valueBet.odds || 2.0).toFixed(2);
      const prob = valueBet.aiProbability || 60;
      const valuePct = valueBet.valuePct || 12;
      const edge = valueBet.edge === 'strong' ? '🔥 STRONG STATISTICAL EDGE' : '⚡ POSITIVE VALUE EDGE';

      textToSend = [
        `💎 <b>PREDICTPRO AI — VALUE BET ALERT</b> 💎`,
        ``,
        `⚽ <b>${home} vs ${away}</b>`,
        `🏆 <i>${league}</i>`,
        `🎯 <b>Target Market:</b> ${market}`,
        `💰 <b>Bookmaker Price:</b> ${odds}`,
        `📊 <b>AI Model Prob.:</b> ${prob}%`,
        `📈 <b>Expected Value (+EV):</b> +${valuePct}% (${edge})`,
        ``,
        `💡 <i>Our Poisson xG model indicates the market has underpriced this probability. Recommended fractional stake: 1-3% bankroll.</i>`,
        ``,
        `🔍 Explore more value edges: https://predictpro.guru/value-bets`,
        `⚠️ <i>Gamble responsibly.</i>`,
      ].join('\n');
    }

    // Task 6: Broadcast Live In-Play Tactical Momentum Alert
    if (action === 'send_live_inplay' && liveInplay) {
      const home = liveInplay.home_team || 'Home';
      const away = liveInplay.away_team || 'Away';
      const league = liveInplay.league || 'Live Match';
      const minute = liveInplay.minute ? `${liveInplay.minute}'` : 'IN-PLAY';
      const score = liveInplay.score || '0 - 0';
      const tip = liveInplay.tip || 'Next Goal Momentum';
      const conf = liveInplay.confidence || 75;
      const pulse = liveInplay.tacticalPulse || 'High pressing intensity suggests impending scoreline movement.';

      textToSend = [
        `🚨 <b>PREDICTPRO AI — LIVE IN-PLAY ALERT</b> 🚨`,
        ``,
        `⚽ <b>${home} ${score} ${away}</b>`,
        `⏱️ <b>Status:</b> <u>${minute}</u> | 🏆 <i>${league}</i>`,
        `🎯 <b>In-Play Call:</b> <b>${tip}</b> (${conf}% Confidence)`,
        ``,
        `🧠 <b>Tactical Momentum Pulse:</b>`,
        `${pulse}`,
        ``,
        `⚡ <i>Live momentum calculated via Gemini In-Play Engine</i>`,
        `📲 Follow live feeds: https://predictpro.guru/live-scores`,
      ].join('\n');
    }

    if (!textToSend) {
      return new Response(JSON.stringify({ success: false, error: 'Message body or valid payload required' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    if (!botToken) {
      console.warn('[telegram-broadcast] TELEGRAM_BOT_TOKEN is not configured in secrets.');
      return new Response(JSON.stringify({
        success: true,
        simulated: true,
        message: 'Telegram bot token not set in secrets. Broadcast was simulated and previewed successfully.',
        previewText: textToSend,
        chatId,
      }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const res = await fetch(`https://api.telegram.org/bot${botToken}/sendMessage`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        chat_id: chatId,
        text: textToSend,
        parse_mode,
        disable_web_page_preview: false,
      }),
    });

    const data = await res.json();

    return new Response(JSON.stringify({
      success: res.ok,
      data,
      chatId,
      previewText: textToSend,
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  } catch (error: any) {
    return new Response(JSON.stringify({ success: false, error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
