import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { SEO } from "@/components/SEO";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Link } from "react-router-dom";
import { Brain, Globe, Shield, TrendingUp, Users, Zap, Mail, Twitter, Youtube } from "lucide-react";

const TEAM = [
  { name: "AI Engine", role: "Google Gemini 1.5 Flash", desc: "Powers all match analysis, confidence scoring and natural language explanations." },
  { name: "Match Data", role: "API-Football + RapidAPI", desc: "Real-time fixtures, form, H2H, standings and player stats from 40+ leagues." },
  { name: "Predictions API", role: "Football Prediction API", desc: "Professional prediction models covering UEFA, CONMEBOL, CONCACAF, AFC and CAF." },
  { name: "Payments", role: "Stripe + Lipana M-Pesa", desc: "Secure card payments worldwide and M-Pesa STK Push for African markets." },
];

const VALUES = [
  { icon: Brain, title: "AI-Powered", desc: "Every prediction is generated by Google Gemini with real match context — form, H2H, standings. No guesswork." },
  { icon: Shield, title: "Transparent", desc: "We show confidence scores and AI reasoning behind every pick. You decide whether to trust it." },
  { icon: Globe, title: "Truly Global", desc: "40+ leagues across 6 continents. Premier League to KPL, La Liga to MLS, AFCON to Champions League." },
  { icon: TrendingUp, title: "Value-Focused", desc: "Our value bet finder identifies statistical edges over bookmaker odds — not just win/lose predictions." },
  { icon: Users, title: "Community", desc: "Community tipsters, leaderboards and tip voting — wisdom of the crowd alongside AI analysis." },
  { icon: Zap, title: "Real-Time", desc: "Live scores, live news, live predictions. Data refreshes every 30 seconds during match hours." },
];

export default function About() {
  return (
    <div className="min-h-screen bg-background">
      <SEO title="About PredictPro | AI Football Predictions" description="PredictPro is a global AI football prediction platform covering 40+ leagues. Powered by Google Gemini AI, API-Football and real match data." />
      <Navbar />
      <main>
        {/* Hero */}
        <section className="container mx-auto px-4 py-28 max-w-4xl text-center">
          <div className="inline-flex items-center gap-2 bg-primary/10 text-primary rounded-full px-4 py-1.5 text-sm font-medium mb-6">
            <Globe className="h-4 w-4" />Global AI Sports Platform
          </div>
          <h1 className="text-5xl font-black mb-4">Built to Help You<br />Bet Smarter</h1>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto leading-relaxed mb-8">
            PredictPro combines professional AI models, real-time football data and community intelligence 
            to give you the clearest possible picture before every match.
          </p>
          <div className="flex gap-3 justify-center">
            <Link to="/best-bets"><Button size="lg" className="gap-2"><Zap className="h-4 w-4" />See Today's Picks</Button></Link>
            <Link to="/predict"><Button variant="outline" size="lg">Try the Predictor</Button></Link>
          </div>
        </section>

        {/* Values */}
        <section className="bg-muted/30 py-16">
          <div className="container mx-auto px-4 max-w-5xl">
            <h2 className="text-2xl font-bold text-center mb-8">Why PredictPro?</h2>
            <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
              {VALUES.map(({ icon: Icon, title, desc }) => (
                <Card key={title} className="border-primary/10 hover:border-primary/30 transition-colors">
                  <CardContent className="p-5">
                    <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center mb-3">
                      <Icon className="h-5 w-5 text-primary" />
                    </div>
                    <h3 className="font-bold mb-1.5">{title}</h3>
                    <p className="text-sm text-muted-foreground leading-relaxed">{desc}</p>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </section>

        {/* Tech Stack */}
        <section className="container mx-auto px-4 py-16 max-w-5xl">
          <h2 className="text-2xl font-bold text-center mb-2">Our Technology Stack</h2>
          <p className="text-muted-foreground text-center mb-8">World-class APIs powering every prediction</p>
          <div className="grid sm:grid-cols-2 gap-4">
            {TEAM.map(t => (
              <Card key={t.name} className="hover:border-primary/20 transition-colors">
                <CardContent className="p-5">
                  <div className="flex items-start gap-4">
                    <div className="w-2 h-2 rounded-full bg-primary flex-shrink-0 mt-2" />
                    <div>
                      <p className="font-bold">{t.name}</p>
                      <p className="text-xs text-primary font-medium mb-1">{t.role}</p>
                      <p className="text-sm text-muted-foreground">{t.desc}</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </section>

        {/* Responsible gambling */}
        <section className="bg-amber-500/10 border-y border-amber-500/20 py-8">
          <div className="container mx-auto px-4 max-w-3xl text-center">
            <Shield className="h-8 w-8 text-amber-600 mx-auto mb-3" />
            <h3 className="font-bold text-lg mb-2">Gamble Responsibly</h3>
            <p className="text-sm text-muted-foreground">
              PredictPro predictions are for informational purposes. Past accuracy doesn't guarantee future results. 
              Only bet what you can afford to lose. If gambling is affecting your life, seek help: 
              <strong className="text-foreground"> Kenya: 0800 723 253</strong>
            </p>
          </div>
        </section>

        {/* Contact */}
        <section className="container mx-auto px-4 py-16 max-w-3xl text-center">
          <h2 className="text-2xl font-bold mb-2">Get in Touch</h2>
          <p className="text-muted-foreground mb-6">Questions, partnerships or feedback — we'd love to hear from you.</p>
          <div className="flex gap-3 justify-center flex-wrap">
            <a href="mailto:support@predictpro.guru">
              <Button variant="outline" className="gap-2"><Mail className="h-4 w-4" />support@predictpro.guru</Button>
            </a>
            <a href="https://twitter.com/PredictProAI" target="_blank" rel="noopener noreferrer">
              <Button variant="outline" className="gap-2"><Twitter className="h-4 w-4" />@PredictProAI</Button>
            </a>
          </div>
        </section>
      </main>
      <Footer />
    </div>
  );
}
