// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-todays-predictions.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.74.0";
import { z } from "npm:zod@^3.25.76";
var list_todays_predictions_default = defineTool({
  name: "list_todays_predictions",
  title: "List today's predictions",
  description: "Returns PredictPro's AI football/sports predictions for today, sorted by confidence. Non-premium only.",
  inputSchema: {
    minConfidence: z.number().min(0).max(100).optional().describe("Minimum confidence percentage (0-100). Defaults to 70."),
    limit: z.number().min(1).max(50).optional().describe("Max results. Defaults to 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ minConfidence, limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
    );
    const start = /* @__PURE__ */ new Date();
    start.setUTCHours(0, 0, 0, 0);
    const end = new Date(start);
    end.setUTCDate(end.getUTCDate() + 1);
    const { data, error } = await supabase.from("predictions").select(
      "match_id, home_team, away_team, league, sport, prediction, confidence, reasoning, match_date, odds_value"
    ).eq("is_premium", false).gte("match_date", start.toISOString()).lt("match_date", end.toISOString()).gte("confidence", minConfidence ?? 70).order("confidence", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { predictions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-upcoming-predictions.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.74.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_upcoming_predictions_default = defineTool2({
  name: "list_upcoming_predictions",
  title: "List upcoming predictions",
  description: "Returns upcoming (future) non-premium predictions within a look-ahead window in days.",
  inputSchema: {
    days: z2.number().min(1).max(14).optional().describe("Look-ahead window in days. Default 3."),
    league: z2.string().optional().describe("Optional league name filter (exact match)."),
    limit: z2.number().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days, league, limit }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
    );
    const now = /* @__PURE__ */ new Date();
    const end = new Date(now.getTime() + (days ?? 3) * 24 * 60 * 60 * 1e3);
    let q = supabase.from("predictions").select("match_id, home_team, away_team, league, sport, prediction, confidence, match_date").eq("is_premium", false).gte("match_date", now.toISOString()).lte("match_date", end.toISOString()).order("match_date", { ascending: true }).limit(limit ?? 20);
    if (league) q = q.eq("league", league);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { matches: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-platform-accuracy.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.74.0";
import { z as z3 } from "npm:zod@^3.25.76";
var get_platform_accuracy_default = defineTool3({
  name: "get_platform_accuracy",
  title: "Get platform accuracy",
  description: "Returns PredictPro's recent overall prediction accuracy statistics (last N days).",
  inputSchema: {
    days: z3.number().min(1).max(90).optional().describe("Number of recent days. Default 30.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
    );
    const { data, error } = await supabase.from("platform_accuracy").select("date, total_predictions, correct_predictions, accuracy_percent, by_league").order("date", { ascending: false }).limit(days ?? 30);
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    const rows = data ?? [];
    const totals = rows.reduce(
      (a, r) => {
        a.total += r.total_predictions ?? 0;
        a.correct += r.correct_predictions ?? 0;
        return a;
      },
      { total: 0, correct: 0 }
    );
    const overall = totals.total > 0 ? totals.correct / totals.total * 100 : 0;
    const summary = {
      window_days: rows.length,
      total_predictions: totals.total,
      correct_predictions: totals.correct,
      overall_accuracy_percent: Math.round(overall * 100) / 100,
      daily: rows
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/list-news.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.74.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_news_default = defineTool4({
  name: "list_news",
  title: "List news articles",
  description: "Returns the most recent published football/sports news articles from PredictPro.",
  inputSchema: {
    limit: z4.number().min(1).max(50).optional().describe("Max articles. Default 10."),
    category: z4.string().optional().describe("Optional category filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, category }) => {
    const supabase = createClient4(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
    );
    let q = supabase.from("news_articles").select("id, title, summary, category, published_at, slug, source_url").order("published_at", { ascending: false }).limit(limit ?? 10);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { articles: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "predictpro-mcp",
  title: "PredictPro MCP",
  version: "0.1.0",
  instructions: "PredictPro is an AI-powered sports prediction platform. Use these tools to read today's and upcoming AI football/sports predictions (with confidence scores and reasoning), platform accuracy statistics, and recent news articles. All results are public/non-premium data.",
  tools: [list_todays_predictions_default, list_upcoming_predictions_default, get_platform_accuracy_default, list_news_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
