// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-todays-predictions.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.74.0";
import { z } from "npm:zod@^3.25.76";
var list_todays_predictions_default = defineTool({
  name: "list_todays_predictions",
  title: "List today's predictions",
  description: "Returns PredictPro's AI football/sports predictions for today, sorted by confidence. Non-premium only.",
  inputSchema: {
    minConfidence: z.number().min(0).max(100).optional().describe("Minimum confidence percentage (0-100). Defaults to 70."),
    limit: z.number().min(1).max(50).optional().describe("Max results. Defaults to 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ minConfidence, limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
    );
    const start = /* @__PURE__ */ new Date();
    start.setUTCHours(0, 0, 0, 0);
    const end = new Date(start);
    end.setUTCDate(end.getUTCDate() + 1);
    const { data, error } = await supabase.from("predictions").select(
      "match_id, home_team, away_team, league, sport, prediction, confidence, reasoning, match_date, odds_value"
    ).eq("is_premium", false).gte("match_date", start.toISOString()).lt("match_date", end.toISOString()).gte("confidence", minConfidence ?? 70).order("confidence", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { predictions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-upcoming-predictions.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.74.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_upcoming_predictions_default = defineTool2({
  name: "list_upcoming_predictions",
  title: "List upcoming predictions",
  description: "Returns upcoming (future) non-premium predictions within a look-ahead window in days.",
  inputSchema: {
    days: z2.number().min(1).max(14).optional().describe("Look-ahead window in days. Default 3."),
    league: z2.string().optional().describe("Optional league name filter (exact match)."),
    limit: z2.number().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days, league, limit }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
    );
    const now = /* @__PURE__ */ new Date();
    const end = new Date(now.getTime() + (days ?? 3) * 24 * 60 * 60 * 1e3);
    let q = supabase.from("predictions").select("match_id, home_team, away_team, league, sport, prediction, confidence, match_date").eq("is_premium", false).gte("match_date", now.toISOString()).lte("match_date", end.toISOString()).order("match_date", { ascending: true }).limit(limit ?? 20);
    if (league) q = q.eq("league", league);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { matches: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-platform-accuracy.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.74.0";
import { z as z3 } from "npm:zod@^3.25.76";
var get_platform_accuracy_default = defineTool3({
  name: "get_platform_accuracy",
  title: "Get platform accuracy",
  description: "Returns PredictPro's recent overall prediction accuracy statistics (last N days).",
  inputSchema: {
    days: z3.number().min(1).max(90).optional().describe("Number of recent days. Default 30.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
    );
    const { data, error } = await supabase.from("platform_accuracy").select("date, total_predictions, correct_predictions, accuracy_percent, by_league").order("date", { ascending: false }).limit(days ?? 30);
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    const rows = data ?? [];
    const totals = rows.reduce(
      (a, r) => {
        a.total += r.total_predictions ?? 0;
        a.correct += r.correct_predictions ?? 0;
        return a;
      },
      { total: 0, correct: 0 }
    );
    const overall = totals.total > 0 ? totals.correct / totals.total * 100 : 0;
    const summary = {
      window_days: rows.length,
      total_predictions: totals.total,
      correct_predictions: totals.correct,
      overall_accuracy_percent: Math.round(overall * 100) / 100,
      daily: rows
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/list-news.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.74.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_news_default = defineTool4({
  name: "list_news",
  title: "List news articles",
  description: "Returns the most recent published football/sports news articles from PredictPro.",
  inputSchema: {
    limit: z4.number().min(1).max(50).optional().describe("Max articles. Default 10."),
    category: z4.string().optional().describe("Optional category filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, category }) => {
    const supabase = createClient4(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
    );
    let q = supabase.from("news_articles").select("id, title, summary, category, published_at, slug, source_url").order("published_at", { ascending: false }).limit(limit ?? 10);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { articles: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-upcoming-matches.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.74.0";
import { z as z5 } from "npm:zod@^3.25.76";
var list_upcoming_matches_default = defineTool5({
  name: "list_upcoming_matches",
  title: "List upcoming matches",
  description: "Returns cached upcoming football matches with predictions and confidence. Sourced from ESPN, TheSportsDB, and Football-Data.org.",
  inputSchema: {
    league: z5.string().optional().describe("Optional league name filter (exact match)."),
    limit: z5.number().min(1).max(50).optional().describe("Max results. Default 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ league, limit }) => {
    const supabase = createClient5(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
    );
    let q = supabase.from("upcoming_matches_cache").select("match_id, home_team, away_team, league, sport, match_date, match_time, prediction, confidence").gte("match_date", (/* @__PURE__ */ new Date()).toISOString()).order("match_date", { ascending: true }).limit(limit ?? 20);
    if (league) q = q.eq("league", league);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { matches: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-expert-analysis.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.74.0";
import { z as z6 } from "npm:zod@^3.25.76";
var get_expert_analysis_default = defineTool6({
  name: "get_expert_analysis",
  title: "Get expert match analysis",
  description: "Returns in-depth expert analysis for a specific match: form breakdown, head-to-head, key stats, injuries, and betting tips.",
  inputSchema: {
    matchId: z6.string().describe("The match_id to fetch analysis for.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ matchId }) => {
    const supabase = createClient6(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
    );
    const { data, error } = await supabase.from("expert_analysis").select("match_id, form_analysis, head_to_head, key_stats, injury_report, betting_tips, created_at").eq("match_id", matchId).order("created_at", { ascending: false }).limit(1).maybeSingle();
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No expert analysis found for match ${matchId}.` }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { analysis: data }
    };
  }
});

// src/lib/mcp/tools/list-transfer-rumors.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient7 } from "npm:@supabase/supabase-js@^2.74.0";
import { z as z7 } from "npm:zod@^3.25.76";
var list_transfer_rumors_default = defineTool7({
  name: "list_transfer_rumors",
  title: "List transfer rumors",
  description: "Returns the latest football transfer rumors with probability scores, source, and target/current clubs.",
  inputSchema: {
    minProbability: z7.number().min(0).max(100).optional().describe("Minimum probability (0-100). Default 0."),
    limit: z7.number().min(1).max(50).optional().describe("Max rumors. Default 15.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ minProbability, limit }) => {
    const supabase = createClient7(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
    );
    const { data, error } = await supabase.from("transfer_rumors").select("player_name, current_club, target_club, transfer_fee, probability, source, headline, is_confirmed, updated_at").gte("probability", minProbability ?? 0).order("updated_at", { ascending: false }).limit(limit ?? 15);
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { rumors: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-active-contests.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient8 } from "npm:@supabase/supabase-js@^2.74.0";
import { z as z8 } from "npm:zod@^3.25.76";
var list_active_contests_default = defineTool8({
  name: "list_active_contests",
  title: "List active contests",
  description: "Returns PredictPro's currently active prediction contests with entry fees, prize pools, and end dates.",
  inputSchema: {
    limit: z8.number().min(1).max(50).optional().describe("Max contests. Default 10.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient8(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
    );
    const { data, error } = await supabase.from("contests").select("id, name, description, entry_fee, prize_pool, start_date, end_date, status").eq("status", "active").order("end_date", { ascending: true }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { contests: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-news-article.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient9 } from "npm:@supabase/supabase-js@^2.74.0";
import { z as z9 } from "npm:zod@^3.25.76";
var get_news_article_default = defineTool9({
  name: "get_news_article",
  title: "Get news article",
  description: "Fetches the full content of a specific news article by slug or ID.",
  inputSchema: {
    slugOrId: z9.string().describe("Article slug or UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slugOrId }) => {
    const supabase = createClient9(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
    );
    const isUuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(slugOrId);
    const { data, error } = await supabase.from("news_articles").select("id, title, slug, content, excerpt, category, tags, author, featured_image, view_count, created_at").eq(isUuid ? "id" : "slug", slugOrId).eq("is_published", true).maybeSingle();
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    if (!data) return { content: [{ type: "text", text: `Article not found: ${slugOrId}` }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { article: data }
    };
  }
});

// src/lib/mcp/tools/get-streak-leaderboard.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient10 } from "npm:@supabase/supabase-js@^2.74.0";
import { z as z10 } from "npm:zod@^3.25.76";
var get_streak_leaderboard_default = defineTool10({
  name: "get_streak_leaderboard",
  title: "Get streak leaderboard",
  description: "Returns the top users by prediction streak (current and longest) with total correct picks and win rates. Usernames are anonymised.",
  inputSchema: {
    metric: z10.enum(["current_streak", "longest_streak", "total_correct"]).optional().describe("Ranking metric. Default longest_streak."),
    limit: z10.number().min(1).max(50).optional().describe("Max rows. Default 10.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ metric, limit }) => {
    const supabase = createClient10(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
    );
    const orderBy = metric ?? "longest_streak";
    const { data, error } = await supabase.from("user_streaks").select("current_streak, longest_streak, total_correct, last_prediction_date").order(orderBy, { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    const ranked = (data ?? []).map((row, i) => ({ rank: i + 1, ...row }));
    return {
      content: [{ type: "text", text: JSON.stringify(ranked, null, 2) }],
      structuredContent: { leaderboard: ranked, metric: orderBy }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "predictpro-mcp",
  title: "PredictPro MCP",
  version: "0.2.0",
  instructions: "PredictPro is an AI-powered sports prediction platform. Read tools cover today's and upcoming AI predictions (with confidence and reasoning), cached upcoming matches, in-depth expert analysis per match, platform accuracy stats, news articles (list + full content), transfer rumors, active prediction contests, and streak leaderboards. All data is public/non-premium.",
  tools: [
    list_todays_predictions_default,
    list_upcoming_predictions_default,
    list_upcoming_matches_default,
    get_expert_analysis_default,
    get_platform_accuracy_default,
    list_news_default,
    get_news_article_default,
    list_transfer_rumors_default,
    list_active_contests_default,
    get_streak_leaderboard_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
